/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'

const SettingsRouteLazyRouteImport = createFileRoute('/settings')()
const IndexLazyRouteImport = createFileRoute('/')()
const SettingsConnectionsLazyRouteImport = createFileRoute(
  '/settings/connections',
)()
const SettingsAccountLazyRouteImport = createFileRoute('/settings/account')()

const SettingsRouteLazyRoute = SettingsRouteLazyRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/settings/route.lazy').then((d) => d.Route),
)
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteLazyRoute,
} as any)
const SettingsConnectionsLazyRoute = SettingsConnectionsLazyRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => SettingsRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/settings/connections.lazy').then((d) => d.Route),
)
const SettingsAccountLazyRoute = SettingsAccountLazyRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SettingsRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/settings/account.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/settings': typeof SettingsRouteLazyRouteWithChildren
  '/settings/account': typeof SettingsAccountLazyRoute
  '/settings/connections': typeof SettingsConnectionsLazyRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/settings/account': typeof SettingsAccountLazyRoute
  '/settings/connections': typeof SettingsConnectionsLazyRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/settings': typeof SettingsRouteLazyRouteWithChildren
  '/settings/account': typeof SettingsAccountLazyRoute
  '/settings/connections': typeof SettingsConnectionsLazyRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/settings/account'
    | '/settings/connections'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings/account' | '/settings/connections' | '/settings'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/settings/account'
    | '/settings/connections'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  SettingsRouteLazyRoute: typeof SettingsRouteLazyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteLazyRoute
    }
    '/settings/connections': {
      id: '/settings/connections'
      path: '/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof SettingsConnectionsLazyRouteImport
      parentRoute: typeof SettingsRouteLazyRoute
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountLazyRouteImport
      parentRoute: typeof SettingsRouteLazyRoute
    }
  }
}

interface SettingsRouteLazyRouteChildren {
  SettingsAccountLazyRoute: typeof SettingsAccountLazyRoute
  SettingsConnectionsLazyRoute: typeof SettingsConnectionsLazyRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteLazyRouteChildren: SettingsRouteLazyRouteChildren = {
  SettingsAccountLazyRoute: SettingsAccountLazyRoute,
  SettingsConnectionsLazyRoute: SettingsConnectionsLazyRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteLazyRouteWithChildren =
  SettingsRouteLazyRoute._addFileChildren(SettingsRouteLazyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  SettingsRouteLazyRoute: SettingsRouteLazyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
